version: "3.8"
services:
    app:
        build:
            dockerfile: Dockerfile.development
            args:
                GITHUB_ACCESS_TOKEN: ${GITHUB_ACCESS_TOKEN}
        volumes:
            - ./env:/var/www/env
