<?php
return [
		'function_title' => '復刻情報',
		'columns' => [
				'id' => [
						'search' => true,
						'listview' => true,
						'col_lg_size' => 6,
						'col_md_size' => 6,
						'col_sm_size' => 12,
				],
				'gasha_id' => [
						'search' => true,
						'listview' => true,
						'label' => 'ガシャID',
						'col_lg_size' => 6,
						'col_md_size' => 6,
						'col_sm_size' => 12,
						'input_type' => 'foreign_key',
						'search_type' => '=',
						'foreign_table' => 'gashas',
						'foreign_disp_column' => 'title',
				],
				'card_id' => [
						'search' => true,
						'listview' => true,
						'label' => 'カードID',
						'col_lg_size' => 6,
						'col_md_size' => 6,
						'col_sm_size' => 12,
						'input_type' => 'foreign_key',
						'search_type' => '=',
						'foreign_table' => 'cards',
						'foreign_disp_column' => 'name',
				],
				'created' => [
						'search' => false,
						'listview' => false,
						'label' => '作成日時',
						'col_lg_size' => 6,
						'col_md_size' => 6,
						'col_sm_size' => 12,
				],
				'modified' => [
						'search' => false,
						'listview' => true,
						'label' => '更新日時',
						'col_lg_size' => 6,
						'col_md_size' => 6,
						'col_sm_size' => 12,
				],
		],
		'options' => [
				'is_search_form' => true,
				'yubinbango' => false,
				'paging_limit' => 20,
				'left_side_menu_icon_class' => 'fas fa-table',
				'google_map_api_key' => '',
				'delete_function' => true,
				'csv_export' => true,
				'csv_import' => false,
		],
];
