<?php
return [
    'function_title' => 'ガシャ',
    'columns' => [
        'id' => [
            'search' => true,
            'listview' => true,
            'require' => false,
            'col_lg_size' => 6,
            'col_md_size' => 6,
            'col_sm_size' => 12,
        ],
        'start_date' => [
            'search' => true,
            'listview' => true,
            'require' => true,
            'label' => 'ガシャ開始日',
            'col_lg_size' => 2,
            'col_md_size' => 2,
            'col_sm_size' => 12,
            'input_type' => 'date',
            'search_type' => '>=',
        ],
        'end_date' => [
            'search' => true,
            'listview' => true,
            'require' => true,
            'label' => 'ガシャ終了日',
            'col_lg_size' => 2,
            'col_md_size' => 2,
            'col_sm_size' => 12,
            'input_type' => 'date',
            'search_type' => '<=',
        ],
        'title' => [
            'search' => true,
            'listview' => true,
            'require' => true,
            'label' => 'ガシャタイトル',
            'col_lg_size' => 8,
            'col_md_size' => 8,
            'col_sm_size' => 12,
            'input_type' => 'text',
            'search_type' => 'LIKE',
        ],
        'ssr_rate' => [
            'search' => false,
            'listview' => true,
            'require' => true,
            'label' => 'SSRレート',
            'col_lg_size' => 2,
            'col_md_size' => 2,
            'col_sm_size' => 12,
            'input_type' => 'number',
            'min_value' => 0,
            'max_value' => 100,
            'step_value' => 1,
            'unit_text' => '%',
        ],
        'sr_rate' => [
            'search' => false,
            'listview' => true,
            'require' => true,
            'label' => 'SRレート',
            'col_lg_size' => 2,
            'col_md_size' => 2,
            'col_sm_size' => 12,
            'input_type' => 'number',
            'min_value' => 0,
            'max_value' => 100,
            'step_value' => 1,
            'unit_text' => '%',
        ],
        'created' => [
            'search' => false,
            'listview' => false,
            'require' => false,
            'label' => '作成日時',
            'col_lg_size' => 6,
            'col_md_size' => 6,
            'col_sm_size' => 12,
        ],
        'modified' => [
            'search' => false,
            'listview' => true,
            'require' => false,
            'label' => '更新日時',
            'col_lg_size' => 6,
            'col_md_size' => 6,
            'col_sm_size' => 12,
        ],
    ],
    'options' => [
        'one_record_limited' => false,
        'is_search_form' => true,
        'yubinbango' => false,
        'paging_limit' => 20,
        'left_side_menu_icon_class' => 'fas fa-database',
        'delete_function' => true,
        'init_order_column' => 'id',
        'init_order_direction' => 'desc',
        'csv_export' => true,
        'csv_import' => true,
    ],
];
