<?php
return [
		'function_title' => 'ガシャ',
		'columns' => [
				'id' => [
						'search' => true,
						'listview' => true,
						'col_md_size' => 6,
						'col_sm_size' => 12,
				],
				'start_date' => [
						'search' => true,
						'listview' => true,
						'label' => 'ガシャ開始日',
						'col_md_size' => 2,
						'col_sm_size' => 12,
						'input_type' => 'date',
				],
				'end_date' => [
						'search' => true,
						'listview' => true,
						'label' => 'ガシャ終了日',
						'col_md_size' => 2,
						'col_sm_size' => 12,
						'input_type' => 'date',
				],
				'title' => [
						'search' => true,
						'listview' => true,
						'label' => 'ガシャタイトル',
						'col_md_size' => 8,
						'col_sm_size' => 12,
						'search_type' => 'LIKE',
				],
				'ssr_rate' => [
						'search' => false,
						'listview' => true,
						'label' => 'SSRレート',
						'col_md_size' => 2,
						'col_sm_size' => 12,
						'input_type' => 'number',
						'min_value' => 0,
						'max_value' => 100,
						'step_value' => 1,
						'unit_text' => '%',
				],
				'sr_rate' => [
						'search' => false,
						'listview' => true,
						'label' => 'SRレート',
						'col_md_size' => 2,
						'col_sm_size' => 12,
						'input_type' => 'number',
						'min_value' => 0,
						'max_value' => 100,
						'step_value' => 1,
						'unit_text' => '%',
				],
				'ssr_pickup_rate' => [
						'search' => false,
						'listview' => true,
						'label' => 'SSRピックアップレート',
						'col_md_size' => 2,
						'col_sm_size' => 12,
						'input_type' => 'number',
						'min_value' => 0,
						'max_value' => 2,
						'step_value' => 0.001,
						'unit_text' => '%',
				],
				'sr_pickup_rate' => [
						'search' => false,
						'listview' => true,
						'label' => 'SRピックアップレート',
						'col_md_size' => 2,
						'col_sm_size' => 12,
						'input_type' => 'number',
						'min_value' => 0,
						'max_value' => 2,
						'step_value' => 0.001,
						'unit_text' => '%',
				],
				'r_pickup_rate' => [
						'search' => false,
						'listview' => true,
						'label' => 'Rピックアップレート',
						'col_md_size' => 2,
						'col_sm_size' => 12,
						'input_type' => 'number',
						'min_value' => 0,
						'max_value' => 20,
						'step_value' => 0.001,
						'unit_text' => '%',
				],
				'created' => [
						'search' => false,
						'listview' => false,
						'label' => '作成日時',
						'col_md_size' => 6,
						'col_sm_size' => 12,
				],
				'modified' => [
						'search' => false,
						'listview' => true,
						'label' => '更新日時',
						'col_md_size' => 6,
						'col_sm_size' => 12,
				],
		],
		'options' => [
				'is_search_form' => true,
				'yubinbango' => false,
				'paging_limit' => 20,
				'left_side_menu_icon_class' => 'fas fa-database',
				'google_map_api_key' => '',
				'delete_function' => true,
				'csv_export' => true,
				'csv_import' => false,
		],
];
